
body = body.toMap();
url = body.get("url");
exp_price = body.get("exp_price");
curr_price = body.get("curr_price");
title = url.remove("https://www.amazon.in/");
i = title.indexOf("/");
title = title.subString(0,i);
title = title.replaceAll("-", " ");
response = Map();
response.put("text","🥳Hurrayyyy! Your awaited item is now available. Hurry and grab this exclusive offer before stocks run out. 🛍️✨ Happy shopping!\n\nProduct Name: " + title + "\nCurrent Price: ₹" + curr_price + "\nExpected Price: ₹" + exp_price + "\n\n🚀Don't miss out on this fantastic deal! 🛒✨");
card = Map();
card.put("title","🎉 **Great News! Price Drop Alert🤩!**");
response.put("card",card);
buttonsList = list();
buttonsList0 = Map();
buttonsList0.put("label","Url");
action = Map();
action.put("type","open.url");
data = Map();
data.put("web",url);
action.put("data",data);
buttonsList0.put("action",action);
buttonsList.add(buttonsList0);
response.put("buttons",buttonsList);
return response;
